package com.infosys.knowledgegap.enums;

public enum NotificationType {
    CRITICAL_GAP,
    MODERATE_GAP,
    CERTIFICATION_EXPIRING,
    CERTIFICATION_EXPIRED,
    ASSESSMENT_REMINDER,
    TRAINING_DEADLINE_APPROACHING,
    TRAINING_DEADLINE_OVERDUE,
    RECOMMENDATION_NEW,
    MENTORSHIP_SESSION_REMINDER,
    MILESTONE_ACHIEVED,
    GENERAL
}
